tasks:
  - init: echo "Replace me with a build script for the project."
    # Specifiy where mongo data is stored
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
    - command: npm install -g @ionic/cli && npm install -g gatsby-cli && npx next -h
    # AWS
    - command: pip install --user virtualenv
    # DigitalOcean
    - command: brew install doctl
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - abusaidm.html-snippets@0.2.1:7b7Vkkp6Lem9WOqKCYMq2w==
    - Zignd.html-css-class-completion@1.19.0:b3YWQQIEP1z3u93nyLX0UA==

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
#     # enable for all branches in this repo (defaults to false)
#     branches: true
#     pullRequestsFromForks: true
#     # enable for pull requests coming from this repo (defaults to true)
#     pullRequests: true
#     # add a check to pull requests (defaults to true)
#     addCheck: true
#     # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
#     addComment: true


# # Command to start on workspace startup (optional)
# tasks:
#   - init: yarn install
#     command: yarn build
# # Ports to expose on workspace startup (optional)
# ports:
#   - port: 8000
#     onOpen: open-preview



