image:
  file: .gitpod.dockerfile

ports:
  - port: 3000
    onOpen: ignore
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - svipas.control-snippets@1.9.1:tTOr8FomaWXl1OyvsZP1SQ==
    # Snippets
    - abusaidm.html-snippets@0.2.1:7b7Vkkp6Lem9WOqKCYMq2w==
    - Zignd.html-css-class-completion@1.19.0:b3YWQQIEP1z3u93nyLX0UA==
    - thekalinga.bootstrap4-vscode@6.1.0:duaQhthWtxWBzXAGe+5GKQ==
    - dsznajder.es7-react-js-snippets@2.8.2:Oslxvz4UUDeKPjbcLgPwdQ==
    - fivethree.vscode-ionic-snippets@2.2.2:Ply5R23KZJUx7j67niwLJQ==
    - fivethree.vscode-svelte-snippets@0.5.0:rRkcaFrMb8wbTuH6kbGEQQ==
    
    # Lint
    - dbaeumer.vscode-eslint@2.1.3:1NRvj3UKNTNwmYjptmUmIw==
    # View Documents
    - bringout.pdf-view@2.2.2:m2alWRlC9L/tyX8kV/oeNg==
    # Documentation
    - joelday.docthis@0.7.1:OOpm9cdbc8T5+PL4o+MM3Q==
    - aaron-bond.better-comments@2.1.0:w1dHZXyFPGn7vpca57Nf5g==
    # SVG
    - jock.svg@1.3.5:saP8NjiKhPIJgolGEL9E3g==
    - idleberg.svg-icons@0.7.0:ktzpetSpTEIdU0RF39/Dgg==

tasks:
  -  command: mkdir /workspace/ionic-webcam-help/logs                              &&
              touch /workspace/ionic-webcam-help/logs/gitpod-install-log.txt       &&
       
       
              echo "Starting .gitpod.yml installation" &>>  /workspace/ionic-webcam-help/logs/gitpod-install-log.txt  &&  
              
              echo "Set bash files to runable"         &>>  /workspace/ionic-webcam-help/logs/gitpod-install-log.txt  &&                 
              chmod +x ./ionic/a01-cordova-create.sh                                                                  &&      
              chmod +x ./ionic/a02-cordova-rebuild.sh                                                                 &&     
              chmod +x ./ionic/a03-android-sdkmanager.sh                                                              && 
              chmod +x ./ionic/a04-ionic-start.sh                                                                     && 
              chmod +x ./ionic/a05-ionic-rebuild.sh                                                                   && 
              chmod +x ./ionic/a06-capacitor-create.sh                                                                && 
              
              chmod -R 775 /home/gitpod/.android                                                                      &&
             
          
   
              echo "Installing Android Platforms "     &>>  /workspace/ionic-webcam-help/logs/gitpod-install-log.txt  &&  
              export ANDROID_SDK_ROOT=" /home/gitpod/.android"                                                        && 

              export PATH="${PATH}:${ANDROID_SDK_ROOT}/tools:${ANDROID_SDK_ROOT}/tools/bin:${ANDROID_SDK_ROOT}/platform-tools"  && 

              echo  $PATH                              &>> /workspace/ionic-webcam-help/logs/gitpod-install-log.txt   &&   
              yes | sdkmanager "platform-tools" "build-tools;28.0.3" "platforms;android-28"                           &&       
              sdkmanager --list                        &>> /workspace/ionic-webcam-help/logs/gitpod-install-log.txt   &&     
             

          
              echo "Starting Apache"                   &>>  /workspace/ionic-webcam-help/logs/gitpod-install-log.txt  &&   
              apachectl start                                                                                               &&
              gp await-port 8001                                                                                            && 
              gp preview $(gp url 8001)                                                                                     &&
              
              
              
              echo "Ending .gitpod.yml installation"  &>>   /workspace/ionic-webcam-help/logs/gitpod-install-log.txt    
              
              